# .streamlit/config.toml

[server]
headless = true
port = 8501
enableCORS = false
enableXsrfProtection = false
fileWatcherType = "auto"

[browser]
gatherUsageStats = false
serverAddress = "localhost"

[theme]
base = "light"
primaryColor = "#4CAF50"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f2f6"
textColor = "#262730"
font = "sans serif"
